name: AssistPurchase

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: AssistPurchase.sln    

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    
    - name: Build with dotnet
      run: dotnet build --configuration Release
      
    - name:  Run tests
      run: dotnet test --no-build --configuration Release
      
